#!/bin/sh

# Carregar caminho do PHP do .env
PHP=$(grep PHP_HERD_PATH .env | cut -d '=' -f2 | tr -d '"')

if [ -z "$PHP" ]; then
  echo "Caminho do PHP não encontrado. Defina PHP_HERD_PATH no .env"
  exit 1
fi

$PHP ./vendor/bin/phpstan

if [ $? -ne 0 ]; then
    echo "Ops! O PHPStan detectou alguns problemas no código. Resolva antes de seguir com o commit."
    exit 1
fi

# Executa os testes
$PHP artisan test --parallel

if [ $? -ne 0 ]; then
    echo "Ops! Algum teste retornou erro. Resolva antes de seguir com o commit."
    exit 1
fi

# Formata arquivos alterados com o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    $PHP ./vendor/bin/pint "${FILE}" > /dev/null >&1
    git add "${FILE}"
done

exit 0
